version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5002
    depends_on:
      - mlflow

  mlflow:
    image: python:3.9
    container_name: mlflow
    # Install MLflow in this container
    command: >
      /bin/bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5002"
    ports:
      - "5002:5002"
    volumes:
      - ./mlruns:/app/mlruns