name: CI Pipeline

on:
  push:
    branches:
      - master  # Run workflow on pushes to the master branch
  pull_request:
    branches:
      - master  # Run workflow on pull requests to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check Docker Compose version to ensure it's installed

      # Step 4: Build and test Docker Compose services
      - name: Build and test Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 20  # Wait for services to come up
          curl --retry 5 --retry-delay 10 --fail http://localhost:5001/predict || exit 1  # Test Flask API
          curl --retry 5 --retry-delay 10 --fail http://localhost:5002 || exit 1  # Test MLflow UI
          
      # Step 5: Tear down the Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose -f docker-compose.yml down